storage_table_left:
  x: 0.2
  y: 0.4
  z: 0.0
storage_table_right:
  x: 0.2
  y: -0.4
  z: 0.0
grey_plate1:
  x: 0.45
  y: -0.065
  z: 0.25
cracker_box:
  x: 0.6
  y: -0.04
  z: 0.4
cup:
  x: 0.55
  y: 0.08
  z: 0.26 
suger:
  x: 0.45
  y: -0.065
  z: 0.3
TomatoSoupCan:
  x: 0.45
  y: 0.06
  z: 0.3  

  